/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cat.prcetrencada.assemblycat.view;

import cat.prcetrencada.assemblycat.model.entitieslayer.Game;
import cat.prcetrencada.assemblycat.model.entitieslayer.Platform;
import cat.prcetrencada.assemblycat.model.enums.PersistanceTech;
import cat.prcetrencada.assemblycat.presenter.fetch.DataFetcherPresenter;
import static cat.prcetrencada.assemblycat.presenter.io.IOPresenter.*;
import java.io.IOException;
import java.net.ConnectException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.concurrent.ExecutionException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Panell Inicial
 * @author @Narx221 Projecte 'Ce' Trencada
 */
public class Start extends JPanel {

    public Start() {
        initComponents();
        if(!isConfigFileCreated()){
            try {
                createConfigFile();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error al guardar la configuració, siusplau, torna-ho a intentar. "+ex.getMessage(), "ERROR", 0);
            }
            startButton.setVisible(false);
        }else{
        try{
            HashMap info = DataFetcherPresenter.getInstance().fetchMatchingData(PersistanceTech.JSON);
            if (info !=null){
                ArrayList<Game> gamesInstalled = (ArrayList<Game>) info.get("gamesInstalledList");
                if (gamesInstalled!=null && !gamesInstalled.isEmpty()){
                    ArrayList<Platform> platformsConfigured = (ArrayList<Platform>) info.get("platformsList");
                    StringBuilder display = new StringBuilder("<html>Plataformes afegides: " +platformsConfigured.size());
                    display.append("<br> Jocs de Ce Trencada trobats: ");
                    display.append(gamesInstalled.size());
                    startButton.setVisible(true);
                    configLabel.setText(display.toString());
               }else{
                  startButton.setVisible(false);
               }
            }
         }catch(IOException | InterruptedException | ExecutionException ex){
             //Capturem totes les excepcions aquí, en aquest context, no necessitem mostrar cap missatge JOptionPanel a l'usuari.  
             configLabel.setText("<html>No hem pogut comprovar quins videojocs teniu instal·lats :(<br>Siusplau, revisa la connexió a internet abans de seguir amb les actualitzacions.");
         }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        introLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        explanationLabel = new javax.swing.JLabel();
        configLabel = new javax.swing.JLabel();
        configButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setToolTipText(null);

        introLabel.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        introLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        introLabel.setText("Benvingut a CATÇEMBLA, l'actualitzador de 'Ce' Trencada");
        introLabel.setToolTipText(null);
        introLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        introLabel.setMaximumSize(new java.awt.Dimension(247, 29));

        startButton.setText("Comença");
        startButton.setAlignmentY(0.0F);
        startButton.setIconTextGap(0);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        explanationLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        explanationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        explanationLabel.setText("<html>Amb aquesta aplicació, podràs actualitzar automàticament els jocs de plataformes com Steam o Epic de 'Ce' Trencada comunitat  i fins i tot afegir noves plataformes. <br>També podràs descarregar qualsevol traducció de 'Ce' trencada comunitat si configures un directori de jocs i a dins hi tens una carpeta amb exactament el mateix nom del joc que a la llista.");
        explanationLabel.setToolTipText(null);
        explanationLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        configLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        configLabel.setText("Abans que res, necessitem que configuris les plataformes que vols actualitzar.");
        configLabel.setToolTipText(null);

        configButton.setText("Configura");
        configButton.setAlignmentY(0.0F);
        configButton.setIconTextGap(0);
        configButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("Llistat de tots els jocs de Ce Trencada Comunitat.");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(configButton)
                .addGap(18, 18, 18)
                .addComponent(startButton)
                .addContainerGap())
            .addComponent(introLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(configLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                        .addComponent(explanationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(introLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(explanationLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(configLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(configButton))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        try {
            Select targetPanel = new Select();
            redirect(getParent(), targetPanel);
        }catch(ExecutionException | ConnectException ex){
            JOptionPane.showMessageDialog(getParent(), "<html>Hi ha hagut un error de connexió.<br>" + ex.getMessage(),"Error" ,0);
        } catch (IOException | InterruptedException ex){
            JOptionPane.showMessageDialog(getParent(), "<html>Hi ha hagut un error al llegir les dades.<br>" + ex.getMessage(),"Error" ,0);
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void configButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configButtonActionPerformed
            Config targetPanel = new Config();
            redirect(getParent(), targetPanel);
    }//GEN-LAST:event_configButtonActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        DataFetcherPresenter.getInstance().openGameList();
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton configButton;
    public javax.swing.JLabel configLabel;
    private javax.swing.JLabel explanationLabel;
    private javax.swing.JLabel introLabel;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables

}
