/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cat.prcetrencada.assemblycat.view;

import cat.prcetrencada.assemblycat.model.entitieslayer.Game;
import java.util.ArrayList;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ScheduledThreadPoolExecutor;
import java.util.concurrent.TimeUnit;
import cat.prcetrencada.assemblycat.presenter.io.UpdatePresenter;

/**
 * Panell d'actualització
 * @author @Narx221 Projecte 'Ce' Trencada
 */
public class Update extends javax.swing.JPanel implements Runnable {
    private final ArrayList<Game> gamesList;
    private int formPropertyChangeEventCounter=0;
    
    /**
     * Crea un nou JPanel Update
     * @param gamesList
     */
    public Update(ArrayList<Game> gamesList) {
        this.gamesList=gamesList;
        initComponents();
        gameLabel.setText(gamesList.get(0).getName());
    }

    //Implementem Interface Runnable per utilitzar el mètode run en un thread diferent.
    @Override
    public void run() {
       UpdatePresenter.getInstance().updateGames(gamesList,this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exceptionLabel = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        introLabel = new javax.swing.JLabel();
        gameLabel = new javax.swing.JLabel();
        retryButton = new javax.swing.JButton();
        logLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        jLabel2.setText("Joc en procés d'actualització:");

        introLabel.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        introLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        introLabel.setText("Actualitzant els jocs seleccionats");
        introLabel.setToolTipText(null);

        gameLabel.setText("GameName");

        retryButton.setVisible(false);
        retryButton.setText("Reintentar");
        retryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                retryButtonMouseReleased(evt);
            }
        });
        retryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retryButtonActionPerformed(evt);
            }
        });

        logLabel.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
            .addComponent(introLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exceptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(retryButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(introLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(gameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(exceptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        formPropertyChangeEventCounter++;
        if(formPropertyChangeEventCounter>=2){
            triggerGameUpdate();
        }
    }//GEN-LAST:event_formPropertyChange

    private void retryButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retryButtonMouseReleased
       run();
    }//GEN-LAST:event_retryButtonMouseReleased

    private void retryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retryButtonActionPerformed

/**
 * Mètode de descàrrega de fitxers, que executa un nou thread separat del Thread Principal.
 * @return 
 */    
private CompletableFuture<Void> triggerGameUpdate(){
    //Es trigeja just quan fa un add component del form amb targetPanel=Update, on Update esta inicialitzat al 100% sense delay
    final ScheduledThreadPoolExecutor executor = new ScheduledThreadPoolExecutor(1);
    executor.schedule(() -> {
        this.run();
    }, 0, TimeUnit.MILLISECONDS);
    return null;
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel exceptionLabel;
    public javax.swing.JLabel gameLabel;
    private javax.swing.JLabel introLabel;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JProgressBar jProgressBar1;
    public javax.swing.JLabel logLabel;
    public javax.swing.JButton retryButton;
    // End of variables declaration//GEN-END:variables
}
